/* TEMPLATE
{title: "N/A", artist: "N/A", notes: [
  { note: "5", delay: 0, length: 0.66 },
]},,
*/

var songs = [

  {title: "Here Without You", artist: "3 Doors Down", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Let Me Go", artist: "3 Doors Down", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Kill", artist: "30 Seconds to Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "If It Means A Lot To You", artist: "A Day To Remember", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Say Something", artist: "A Great Big World ft. Christina Aguilera", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Take On Me", artist: "A-ha", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Renegade", artist: "Aaryan Shah", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Chiquitita", artist: "ABBA", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dancing Queen", artist: "ABBA", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Winner Takes It All", artist: "ABBA", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Easy On Me", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hello", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Make You Feel My Love", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Rolling In The Deep (Easy Piano Tutorial)", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Send My Love (To Your New Lover)", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Set Fire To The Rain", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Skyfall", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Someone Like You", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Someone Like You", artist: "Adele", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dream On", artist: "Aerosmith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Don't Want to Miss a Thing", artist: "Aerosmith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The DJ Is Crying for Help", artist: "AJR", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "World's Smallest Violin", artist: "AJR", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Alone", artist: "Alan Walker", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Darkside", artist: "Alan Walker", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Faded", artist: "Alan Walker", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Faded", artist: "Alan Walker", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Spectre", artist: "Alan Walker", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lily", artist: "Alan Walker, K-391 & Emelie Hollow", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "On My Way", artist: "Alan Walker, Sabrina Carpenter & Farruko", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Devil Doesn't Bargain", artist: "Alec Benjamin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Let Me Down Slowly", artist: "Alec Benjamin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Our Love Is A Burning Garden", artist: "Alec Benjamin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Shadow of Mine", artist: "Alec Benjamin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Queen of Kings", artist: "Alessandra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fairytale", artist: "Alexander Rybak", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "New Moon (The Meadow)", artist: "Alexandre Desplat", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Back To Black", artist: "Amy Winehouse", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Rise Up", artist: "Andra Day", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Don't Give Up On Me", artist: "Andy Grammer", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Am Yours", artist: "Andy Grammer", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Breathe", artist: "Anna Nalick", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Peter Pan Was Right", artist: "Anson Seabra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Walked Through Hell", artist: "Anson Seabra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "7 Rings", artist: "Ariana Grande", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Into You", artist: "Ariana Grande", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Till Forever Falls Apart", artist: "Ashe & Finneas", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Moral of the Story", artist: "Ashe", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Vogel im Käfig", artist: "Attack on Titan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Runaway", artist: "Aurora", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heaven", artist: "Avicii", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Nights", artist: "Avicii", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wake Me Up", artist: "Avicii", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Complicated", artist: "Avril Lavigne", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I'm WIth You", artist: "Avril Lavigne", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Met Sarah In The Bathroom", artist: "Awfultune", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "BWV 974 Concerto in D Minor", artist: "Bach Marcelo Adagio", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Want It That Way", artist: "Backstreet Boys", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Got It In You", artist: "Banners", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Someone To You", artist: "Banners", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Pompeii", artist: "Bastille", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Denk Maar Niet Aan Morgen", artist: "Bazart", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Started a Joke", artist: "Bee Gees", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stayin' Alive", artist: "Bee Gees", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Für Elise", artist: "Beethoven", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Moonlight Sonata", artist: "Beethoven", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Build a Bitch", artist: "Bella Poarch", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stand by Me", artist: "Ben E. King", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bad Decisions", artist: "Benny Blanco, BTS & Snoop Dogg", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ghost Town", artist: "Benson Boone", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "In The Stars", artist: "Benson Boone", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Take My Breath Away", artist: "Berlin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bad Guy", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happier Than Ever", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Love You", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "idontwannabeyouanymore", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Listen Before I Go", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lost Cause", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "No Time to Die (Advanced)", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "No Time to Die", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ocean Eyes", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "TV", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "When the Party's Over", artist: "Billie Eilish", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lovely", artist: "Billie Eilish, Khalid", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Eyes Without a Face", artist: "Billy Idol", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Let It All Go ft. Rhodes", artist: "Birdy & Rhodes", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Not About Angels", artist: "Birdy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "People Help The People", artist: "Birdy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wings", artist: "Birdy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hard to Love", artist: "Blackpink", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Miss You", artist: "Blink-182", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Jingle Bell Rock (Christmas)", artist: "Bobby Helms", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Roslyn", artist: "Bon Iver & St. Vincent", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "It's My Life", artist: "Bon Jovi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Misunderstood", artist: "Bon Jovi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Understand", artist: "BoyWithUke", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Breath", artist: "Breaking Benjamin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dear Agony", artist: "Breaking Benjamin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Give Me a Sign", artist: "Breaking Benjamin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Some Days", artist: "Brent Morgan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Neon Moon", artist: "Brooks & Dunn", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Count on Me", artist: "Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Grenade", artist: "Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "It Will Rain", artist: "Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Just The Way You Are", artist: "Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Locked Out of Heaven", artist: "Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Talking to the Moon", artist: "Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "When I Was Your Man", artist: "Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "(Everything I Do) I Do It For You", artist: "Bryan Adams", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heaven", artist: "Bryan Adams", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Will Always Return", artist: "Bryan Adams", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dynamite", artist: "BTS", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bridges", artist: "Calum Scott", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dancing On My Own", artist: "Calum Scott", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You Are The Reason", artist: "Calum Scott", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Safe and Sound", artist: "Capital Cities", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bella's Lullaby (Twilight)", artist: "Carter Burwell", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Know What You Are (Twilight Soundtrack)", artist: "Carter Burwell", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All by Myself (Advanced)", artist: "Celine Dion", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "It's All Coming Back To Me Now", artist: "Celine Dion", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: null, artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "See You Again", artist: "Charlie Puth", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Don't Talk Anymore", artist: "Charlie Puth ft. Selena Gomez", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Me and Your Mama", artist: "Childish Gambino", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hold On", artist: "Chord Overstreet", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Under the Influence", artist: "Chris Brown", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wicked Game", artist: "Chris Isaak", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Tennessee Whiskey", artist: "Chris Stapleton", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "A Thousand Years", artist: "Christina Perri", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "A Thousand Years", artist: "Christina Perri", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Jar of Hearts", artist: "Christina Perri", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Carol of the Bells", artist: "Christmas", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Deck the Halls", artist: "Christmas", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Frosty the Snowman", artist: "Christmas", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Three Kings", artist: "Christmas", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All For You", artist: "Cian Ducrot", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I'll Be Waiting", artist: "Cian Ducrot", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Guess I'm In Love", artist: "Clinton Kane", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Zach Sobiech", artist: "Clouds", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Remember Me", artist: "Coco", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Coffin Dance", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Try", artist: "Colbie Caillat", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "A Sky Full of Stars", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Clocks", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Clocks", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fix You", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "In My Place", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Paradise", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sparks", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Scientist", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Viva La Vida", artist: "Coldplay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "My Universe", artist: "Coldplay X BTS", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Memories", artist: "Conan Gray", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Reckless Love", artist: "Cory Asbury", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Don't Stop Dancing", artist: "Creed", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Have You Ever Seen The Rain", artist: "Creedence Clearwater Revival", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Edith's Theme", artist: "Crimson Peak", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Here With Me", artist: "d4vd", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Romantic Homicide", artist: "d4vd", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Blower's Daughter", artist: "Damien Rice", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dragon Ball GT", artist: "Dan Dan Kokoro Hikareteku", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dancing in the Sky", artist: "Dani and Lizzy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bad Day", artist: "Daniel Powter", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Life After You", artist: "Daughtry", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "No Surprise", artist: "Daughtry", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Glorious", artist: "David Archuleta", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I'm Good (Blue)", artist: "David Guetta & Bebe Rexha", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Without You", artist: "David Guetta ft. Usher", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Daylight", artist: "David Kushner", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Be Alright", artist: "Dean Lewis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "How Do I Say Goodbye", artist: "Dean Lewis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lose My Mind", artist: "Dean Lewis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Powfu ft. Beabadoobee", artist: "Death Bed", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dream It Possible", artist: "Delacey", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Give Your Heart a Break", artist: "Demi Lovato", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sober", artist: "Demi Lovato", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Tell Me You Love Me", artist: "Demi Lovato", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Better Days", artist: "Dermot Kennedy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Outnumbered", artist: "Dermot Kennedy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Solstice of Heroes 2022 Soundtrack", artist: "Destiny 2", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Thank You", artist: "Dido", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Sound of Silence", artist: "Disturbed", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Limit Break x Survivor", artist: "Dragon Ball Super", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cha-La Head-Cha-La", artist: "Dragon Ball Z", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ordinary World", artist: "Duran Duran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Birthday Cake", artist: "Dylan Conrique", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Joker and the Queen", artist: "Ed Sheeran & Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All of the Stars", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bad Habits", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Boat", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Castle on the Hill", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Eyes Closed", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happier", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lego House", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Perfect", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Photograph", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Shape of You", artist: "Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Crazy In Love", artist: "Eden feat. Leah Kelly", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Home", artist: "Edith Whiskers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Pomp and Circumstance", artist: "Edward Elgar", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "O Come To The Altar", artist: "Elevation Worship", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Yours", artist: "Ella Henderson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Middle of the Night", artist: "Elley Duhé", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Love Me Like You Do", artist: "Ellie Goulding", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Can You Feel The Love Tonight (The Lion King)", artist: "Elton John", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Goodbye Yellow Brick Road", artist: "Elton John", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "After All", artist: "Elton John, Charlie Puth", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cold Heart (PNAU Remix)", artist: "Elton John, Dua Lipa", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Can't Help Falling in Love", artist: "Elvis Presley", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Suspicious Minds", artist: "Elvis Presley", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sugar Crash!", artist: "ElyOtto", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Numb Little Bug", artist: "Em Beihold", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lose Yourself", artist: "Eminem", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mockingbird", artist: "Eminem", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Don't Talk About Bruno", artist: "Encanto", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Only Time", artist: "Enya", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "California", artist: "Ethan Dufalt", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Final Countdown", artist: "Europe", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bring Me To Life", artist: "Evanescence", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hello", artist: "Evanescence", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lithium", artist: "Evanescence", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "My Immortal", artist: "Evanescence", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "My Immortal", artist: "Evanescence", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Centuries", artist: "Fall Out Boy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Take Over, The Breaks Over", artist: "Fall Out Boy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cupid", artist: "Fifty Fifty", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Superman", artist: "Five For Fighting", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Riddle", artist: "Five For Fighting", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ylang Ylang", artist: "FKJ", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Best of You", artist: "Foo Fighters", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fly Me To The Moon", artist: "Frank Sinatra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lost Without You", artist: "Freya Ridings", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Are Young ft. Janelle Monáe", artist: "Fun", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Home", artist: "Gabrielle Aplin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Power of Love", artist: "Gabrielle Aplin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Gold Dust", artist: "Galantis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Dance", artist: "Garth Brooks", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mad World", artist: "Gary Jules", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Not Over You", artist: "Gavin DeGraw", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Always", artist: "Gavin James", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "ABCDEFU", artist: "Gayle", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Green Green Grass", artist: "George Ezra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hold My Girl", artist: "George Ezra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Careless Whisper", artist: "George Michael", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Careless Whisper", artist: "George Michael", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mary on a Cross", artist: "Ghost", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Giorno's Theme (JoJo's Bizarre Adventure Golden Wind OST)", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heartbreak Anniversary", artist: "Giveon", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Now We Are Free", artist: "Gladiator", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heat Waves", artist: "Glass Animals", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Iris", artist: "Goo Goo Dolls", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Name", artist: "Goo Goo Dolls", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Somebody That I Used To Know", artist: "Gotye ft. Kimbra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "21 Guns", artist: "Green Day", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Boulevard of Broken Dreams", artist: "Green Day", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wake Me Up When September Ends", artist: "Green Day", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Interstellar Main Theme", artist: "Hans Zimmer", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Time", artist: "Hans Zimmer", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Time", artist: "Hans Zimmer", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hedwig's Theme", artist: "Harry Potter", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "As It Was", artist: "Harry Styles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Falling", artist: "Harry Styles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fine Line", artist: "Harry Styles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Satellite", artist: "Harry Styles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sign of the Times", artist: "Harry Styles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Éternel", artist: "Hatik", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Changes", artist: "Hayd", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Superhero", artist: "Hayd", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Addict", artist: "Hazbin Hotel", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Oceans (Where Feet May Fail)", artist: "Hillsong United", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lips Of An Angel", artist: "Hinder", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Reason", artist: "Hoobastank", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Merry Go Round of Life (Joe Hisaishi)", artist: "Howl's Moving Castle", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cherry Wine", artist: "Hozier", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Take Me to Church", artist: "Hozier", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Would That I", artist: "Hozier", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All Night", artist: "Icona Pop", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heart of Stone", artist: "Iko", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bad Liar", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Believer", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Birds", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bones", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Demons", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Natural", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Radioactive", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wrecked", artist: "Imagine Dragons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Enemy", artist: "Imagine Dragons x J.I.D", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Both", artist: "Ingrid Andress", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Flightless Bird, American Mouth", artist: "Iron & Wine", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Broken", artist: "Isak Danielson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ending", artist: "Isak Danielson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hold My Hand", artist: "Isak Danielson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "If You Ever Forget That You Love Me", artist: "Isak Danielson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Power", artist: "Isak Danielson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Somewhere Over The Rainbow", artist: "Israel IZ Kamakawiwoʻole", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Peaches (The Super Mario Bros. Movie)", artist: "Jack Black", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Working For You", artist: "Jake Scott", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Can I Be Him", artist: "James Arthur", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Car's Outside", artist: "James Arthur", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Falling Like The Stars", artist: "James Arthur", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Impossible", artist: "James Arthur", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Maybe", artist: "James Arthur", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Say You Won't Let Go", artist: "James Arthur", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Train Wreck", artist: "James Arthur", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Let It Go", artist: "James Bay", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Monsters", artist: "James Blunt", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Same Mistake", artist: "James Blunt", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You're Beautiful", artist: "James Blunt", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Solas", artist: "Jamie Duffy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Overdose", artist: "Jamie Foxx", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The City's Yours", artist: "Jamie Foxx", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heroes Tonight", artist: "Janji", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Savage Love", artist: "Jason Derulo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "If We Were Vampires (Easy Piano Tutorial)", artist: "Jason Isbell", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "93 Million Miles", artist: "Jason Mraz", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Won't Give Up", artist: "Jason Mraz", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Greatest Works of Art", artist: "Jay Chou", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Still Wandering", artist: "Jay Chou", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happiest Year", artist: "Jaymes Young", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Infinity", artist: "Jaymes Young", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Find Me In The River", artist: "Jeremy Camp", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You Were Good To Me (Easy Piano Tutorial)", artist: "Jeremy Zucker, Chelsea Cutler", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Te Esperé", artist: "Jesse & Joy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "¡Corre!", artist: "Jesse & Joy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Pray", artist: "Jessie Murph", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Say You Love Me", artist: "Jessie Ware", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Jingle Bells", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Flower", artist: "Jisoo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Take Me Home, Country Roads", artist: "John Denver", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All of Me", artist: "John Legend", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happy Xmas (War Is Over)", artist: "John Lennon", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Imagine", artist: "John Lennon", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Jealous Guy", artist: "John Lennon", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hurt", artist: "Johnny Cash", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Die For You", artist: "Joji", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Glimpse of Us", artist: "Joji", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Glimpse of Us", artist: "Joji", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Like You Do", artist: "Joji", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "When You Look Me In The Eyes", artist: "Jonas Brothers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Faithfully", artist: "Journey", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "If The World Was Ending ft. Julia Michaels", artist: "JP Saxe", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Anyone", artist: "Justin Bieber", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Can't Stop the Feeling", artist: "Justin Timberlake", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Golden Hour", artist: "JVKE", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All The Pretty Girls", artist: "Kaleo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Way Down We Go", artist: "Kaleo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Runaway", artist: "Kanye West", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Roar", artist: "Kary Perry", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Running Up That Hill (Stranger Things)", artist: "Kate Bush", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Monsters", artist: "Katie Sky", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Teenage Dream", artist: "Katy Perry", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The One That Got Away", artist: "Katy Perry", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Somewhere Only We Know", artist: "Keane", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Breakaway", artist: "Kelly Clarkson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Through The Years", artist: "Kenny Rogers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You Decorated My Life", artist: "Kenny Rogers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fantasy", artist: "Khai Dreams", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Coaster", artist: "Khalid", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Use Somebody", artist: "Kings of Leon", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wait For Me", artist: "Kings of Leon", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All I Want", artist: "Kodaline", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Brother", artist: "Kodaline", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Everyone Changes", artist: "Kodaline", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Everything Works Out In The End", artist: "Kodaline", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Would Stay", artist: "Krezip", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lose Somebody", artist: "Kygo, OneRepublic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "City of Stars", artist: "La La Land", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mia & Sebastian's Theme", artist: "La La Land", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "La Vie En Rose", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Jealous", artist: "Labrinth", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Need You Now", artist: "Lady Antebellum", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Always Remember Us This Way", artist: "Lady Gaga", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bad Romance", artist: "Lady Gaga", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bloody Mary", artist: "Lady Gaga", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hold My Hand (Top Gun Maverick)", artist: "Lady Gaga", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Million Reasons", artist: "Lady Gaga", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Shallow", artist: "Lady Gaga, Bradley Cooper", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Summertime Sadness", artist: "Lana Del Rey", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Something", artist: "Lasgo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Strani Amori", artist: "Laura Pausini", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Rescue", artist: "Lauren Daigle", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You Say", artist: "Lauren Daigle", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fingers Crossed", artist: "Lauren Spencer Smith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "10 Things I Hate About You", artist: "Leah Kate", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Run", artist: "Leona Lewis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hallelujah", artist: "Leonard Cohen", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Before You Go", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Before You Go", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bruises", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Forget Me", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hold Me While You Wait", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Pointless", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Someone You Loved", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wish You The Best", artist: "Lewis Capaldi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hanging by a Moment", artist: "Lifehouse", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "MONTERO (Call Me By Your Name)", artist: "Lil Nas X", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Falling Down", artist: "Lil Peep & XXXTENTACION", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Crash, U Crash", artist: "Lil Peep ft. Lil Tracy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mirror", artist: "Lil Wayne ft. Bruno Mars", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Behind Blue Eyes", artist: "Limp Bizkit", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Long Long Time", artist: "Linda Ronstadt", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Crawling", artist: "Linkin Park", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "In The End", artist: "Linkin Park", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lost", artist: "Linkin Park", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fairytale", artist: "Livingston", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ceilings", artist: "Lizzy McAlpine", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Reckless Driving", artist: "Lizzy McAlpine", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Night We Met", artist: "Lord Huron", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Tattoo", artist: "Loreen", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Diverine", artist: "Ludovico Einaudi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Experience", artist: "Ludovico Einaudi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Giorni", artist: "Ludovico Einaudi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nuvole Bianche", artist: "Ludovico Einaudi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nuvole Bianche", artist: "Ludovico Einaudi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Una Mattina", artist: "Ludovico Einaudi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Despacito", artist: "Luis Fonsi ft. Daddy Yankee", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "7 Years", artist: "Lukas Graham", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Love Someone", artist: "Lukas Graham", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Autumn Keys", artist: "Luvtea", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wait", artist: "M83", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Congratulations", artist: "Mac Miller", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Love Lost", artist: "Mac Miller", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fat Funny Friend", artist: "Maddie Zahm", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bajo El Agua", artist: "Manuel Medrano", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Walking in Memphis", artist: "Marc Cohn", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All I Want For Christmas Is You", artist: "Mariah Carey", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Paper Roses", artist: "Marie Osmond", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Animals", artist: "Maroon 5", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Girls Like You ft. Cardi B", artist: "Maroon 5", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Payphone", artist: "Maroon 5", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "She WIll Be Loved", artist: "Maroon 5", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sugar", artist: "Maroon 5", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happier", artist: "Marshmello ft. Bastille", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hero", artist: "Martin Garrix ft. JVKE", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Astronaut in the Ocean", artist: "Masked Wolf", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "This Room", artist: "Matt Cooper", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "As the World Caves In", artist: "Matt Maltese", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Touch", artist: "Mattia Cupelli", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Better When I’m Dancing", artist: "Meghan Trainor", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nothing Else Matters", artist: "Metallica", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "One", artist: "Metallica", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Creepin'", artist: "Metro Boomin, The Weeknd, 21 Savage", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Home", artist: "Michael Bublé", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I'll Never Not Love You", artist: "Michael Bublé", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "It's Beginning To Look a Lot of Christmas", artist: "Michael Bublé", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Beat It", artist: "Michael Jackson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Earth Song", artist: "Michael Jackson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You Are Not Alone", artist: "Michael Jackson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Halloween Theme", artist: "Michael Myers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Falling Apart", artist: "Michael Schulte", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Angels Like You", artist: "Miley Cyrus", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Flowers", artist: "Miley Cyrus", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mortal Kombat Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hayloft (Hard)", artist: "Mother Mother", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nothing Really Matters", artist: "Mr. Probz", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Waves", artist: "Mr. Probz", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "After Dark", artist: "Mr.Kitty", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cancer", artist: "My Chemical Romance", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Don't Love You", artist: "My Chemical Romance", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Beggin'", artist: "Måneskin", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hokage Funeral", artist: "Naruto", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sadness and Sorrow", artist: "Naruto", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Blue Bird", artist: "Naruto Shippuden", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Samidare (Early Summer Rain)", artist: "Naruto Shippuden", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Torn", artist: "Natalie Imbruglia", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Surrender", artist: "Natalie Taylor", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wellerman (Sea Shanty)", artist: "Nathan Evans", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Don't Forget Me", artist: "Nathan Wagner", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "So Sick", artist: "Ne-Yo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Those Eyes", artist: "New West", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Let You Down", artist: "NF", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Paralyzed", artist: "NF", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Trauma", artist: "NF", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Still", artist: "Niall Horan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "This Town", artist: "Niall Horan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Far Away", artist: "Nickelback", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "How You Remind Me", artist: "Nickelback", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Grand Piano", artist: "Nicki Minaj", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sunroof", artist: "Nicky Youre & Dazy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Am I Wrong", artist: "Nico & Vinz", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happy", artist: "Nico Collins", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heart-Shaped Box", artist: "Nirvana", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hurt Somebody", artist: "Noah Kanan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Keep Me", artist: "Novo Amor", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "O Christmas Tree", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Don't Look Back In Anger", artist: "Oasis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stop Crying Your Heart Out", artist: "Oasis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Talk Tonight", artist: "Oasis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wonderwall", artist: "Oasis", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Little Talks", artist: "Of Monsters And Men", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Deja Vu", artist: "Olivia Rodrigo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "good 4 u", artist: "Olivia Rodrigo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happier", artist: "Olivia Rodrigo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Rose Song", artist: "Olivia Rodrigo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Traitor", artist: "Olivia Rodrigo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Irresistible", artist: "One Direction", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Night Changes", artist: "One Direction", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Story of My Life", artist: "One Direction", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "What Makes You Beautiful", artist: "One Direction", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You & I", artist: "One Direction", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Go! (Opening 15)", artist: "One Piece", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Chizu Ga Nakutemo Modoru Kara", artist: "One Punch Man", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Snowfall", artist: "Oneheart x Reidenshi", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Counting Stars", artist: "OneRepublic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Ain't Worried", artist: "OneRepublic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Lived", artist: "OneRepublic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "If I Lose Myself", artist: "OneRepublic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stop and Stare", artist: "OneRepublic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fireflies", artist: "Owl City", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Just Give Me a Reason ft. Nate Ruess", artist: "P!nk", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Perfect", artist: "P!nk", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Canon in D", artist: "Pachelbel", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Only Love Can Hurt Like This", artist: "Paloma Faith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Only Love Can Hurt Like This (Slowed Version)", artist: "Paloma Faith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "House of Memories", artist: "Panic! At the Disco", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "This is Gospel", artist: "Panic! At the Disco", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Only Exception", artist: "Paramore", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Let Her Go", artist: "Passenger", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Belong", artist: "Pat Benatar", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Je Te Laisserai Des Mots", artist: "Patrick Watson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lighthouse", artist: "Patrick Watson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mariage d'Amour", artist: "Paul de Senneville", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You'll Be In My Heart", artist: "Phil Collins", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Home", artist: "Phillip Phillips", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Baby Shark", artist: "Pinkfong", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "He's a Pirate", artist: "Pirates of the Caribbean", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fell This Moment ft. Christina Aguilera", artist: "Pitbull", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Where Is My Mind", artist: "Pixies", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Beautiful James", artist: "Placebo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Bitter End", artist: "Placebo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hey There Delilah", artist: "Plain White T's", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Immortal", artist: "Playboi Carti", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Pokemon Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Wanna Live Meme ft. Huggy Wuggy", artist: "Poppy Playtime", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Circles", artist: "Post Malone", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Eyes Off You", artist: "PRETTYMUCH", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bohemian Rhapsody", artist: "Queen", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Love Of My Life", artist: "Queen", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "These Are The Days of Our Lives", artist: "Queen", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Are The Champions", artist: "Queen", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Creep", artist: "Radiohead", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Reckoner", artist: "Radiohead", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Escapism. ft. 070 Shake", artist: "Raye", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Inalcanzable", artist: "RBD", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hymn for the Missing", artist: "Red", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Californication", artist: "Red Hot Chili Peppers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Two Birds", artist: "Regina Spektor", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ballade Pour Adeline", artist: "Richard Claydeman", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Right Here Waiting", artist: "Richard Marx", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "California King Bed", artist: "Rihanna", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Diamonds", artist: "Rihanna", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lift Me Up", artist: "Rihanna", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Take a Bow", artist: "Rihanna", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "We Found Love ft. Calvin Harris", artist: "Rihanna", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stay", artist: "Rihanna ft. Mikky Ekko", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fighting For Me", artist: "Riley Clemmons", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "La Bamba", artist: "Ritchie Valens", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Shine Your Light", artist: "Robbie Robertson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Angels", artist: "Robbie Williams", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Here I Come", artist: "Roblox Doors", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "A Drop in the Ocean", artist: "Ron Pope", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Snap", artist: "Rosa Linn", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hunger", artist: "Ross Copperman", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "It Must Have Been Love", artist: "Roxette", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Other Side", artist: "Ruelle", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "War of Hearts", artist: "Ruelle", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hallelujah", artist: "Rufus Wainwright", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Closer To The Heart", artist: "Rush", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dandelions", artist: "Ruth B.", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lost Boy", artist: "Ruth B.", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fire On Fire", artist: "Sam Smith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I'm Not The Only One", artist: "Sam Smith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Like I Can", artist: "Sam Smith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stay with Me", artist: "Sam Smith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Too Good at Goodbyes", artist: "Sam Smith", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Unholy", artist: "Sam Smith ft. Kim Petras", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Who We Love", artist: "Sam Smith, Ed Sheeran", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Love Goes", artist: "Sam Smith, Labrinth", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dancing With A Stranger", artist: "Sam Smith, Normani", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lose It All", artist: "Sam Tompkins", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "She Used To Be Mine", artist: "Sara Bareilles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Angel", artist: "Sarah McLachlan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Holding On To Letting Go", artist: "Scott Quinn", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Atlantis", artist: "Seafret", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fall For You", artist: "Secondhand Serenade", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Broken", artist: "Seether ft. Amy Lee", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lose You To Love Me", artist: "Selena Gomez", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Don't Let Me Go", artist: "Sem Eisinger", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Waka Waka (This Time For Africa)", artist: "Shakira", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "In My Blood", artist: "Shawn Mendes", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "It'll Be Okay", artist: "Shawn Mendes", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mercy", artist: "Shawn Mendes", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stitches", artist: "Shawn Mendes", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "There's Nothing Holding Me Back", artist: "Shawn Mendes", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Treat You Better", artist: "Shawn Mendes", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Señorita", artist: "Shawn Mendes, Camila Cabello", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Not The Same", artist: "Sheldon Riley", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Chandelier", artist: "Sia", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cheap Thrills", artist: "Sia", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Elastic Heart", artist: "Sia", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Snowman", artist: "Sia", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Unstoppable", artist: "Sia", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Silent Night", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Welcome to My Life", artist: "Simple Plan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stars", artist: "Simply Red", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hard 4 Me 2 Love You", artist: "Sinead Harnett", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Love Is Gone", artist: "Slander ft. Dylan Matthew", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Aqua Regia", artist: "Sleep Token", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Atlantic", artist: "Sleep Token", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Blood Sport", artist: "Sleep Token", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Levitate", artist: "Sleep Token", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Already Gone", artist: "Sleeping at Last", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heart", artist: "Sleeping at Last", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Neptune", artist: "Sleeping at Last", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Saturn", artist: "Sleeping At Last", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Saturn", artist: "Sleeping At Last", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Touch", artist: "Sleeping At Last", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Turning Page", artist: "Sleeping at Last", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All Star", artist: "Smash Mouth", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Chasing Cars", artist: "Snow Patrol", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Come Back Home", artist: "Sofia Carson", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Disney's Beauty and the Beast", artist: "Something There", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "September", artist: "Sparky Deathcap", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Spooky Scary Skeletons", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Pink Soldiers", artist: "Squid Game", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Red Light, Green Light (Easy to Impossible)", artist: "Squid Game", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Something To Remind You", artist: "Staind", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Evangeline", artist: "Stephen Sanchez", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Until I Found You", artist: "Stephen Sanchez", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Until I Found You", artist: "Stephen Sanchez", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stranger Things Main Theme (Advanced)", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stranger Things Main Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Super Mario Bros Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Wanted to Leave", artist: "SYML", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Where's My Love", artist: "SYML", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Kill Bill", artist: "SZA", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nobody Gets Me", artist: "SZA", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dynamite", artist: "Taio Cruz", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You Broke Me First", artist: "Tate McRae", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "All The Things She Said", artist: "Tatu", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Anti-Hero", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Blank Space", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cardigan", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Enchanted", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fearless", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mean", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Our Song", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Willow", artist: "Taylor Swift", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Pearl Harbor", artist: "Tennessee", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Main Theme", artist: "The Avengers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Main Theme", artist: "The Avengers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hey Jude", artist: "The Beatles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Let It Be", artist: "The Beatles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Yesterday", artist: "The Beatles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Yesterday", artist: "The Beatles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wherever You Will Go", artist: "The Calling", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sick Boy", artist: "The Chainsmokers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Don't Let Me Down", artist: "The Chainsmokers ft. Daya", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Travelin' Soldier", artist: "The Chicks", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "To Build a Home", artist: "The Cinematic Orchestra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "To Build a Home", artist: "The Cinematic Orchestra", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Zombie", artist: "The Cranberries", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "How To Save a Life", artist: "The Fray", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Look After You", artist: "The Fray", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Never Say Never", artist: "The Fray", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Over My Head (Cable Car)", artist: "The Fray", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Rosemary's Theme", artist: "The Giver", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Never Enough", artist: "The Greatest Showman", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "In This Shirt", artist: "The Irrepressibles", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Thousand Miles", artist: "The Kid LAROI", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Without You", artist: "The Kid LAROI", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stay", artist: "The Kid LAROI, Justin Bieber", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Last of Us Main Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cleopatra", artist: "The Lumineers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Ophelia", artist: "The Lumineers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Sleep On The Floor", artist: "The Lumineers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nervous", artist: "The Neighbourhood", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Bloom", artist: "The Paper Kites", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Pink Panther Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Every Breath You Take", artist: "The Police", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Message In A Bottle", artist: "The Police", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Breakeven", artist: "The Script", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "For The First Time", artist: "The Script", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hall of Fame", artist: "The Script", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Back to the Old House", artist: "The Smiths", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Do-Re-Mi", artist: "The Sound of Music", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Somebody To You", artist: "The Vamps ft. Demi Lovato", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Glad You Came", artist: "The Wanted", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Blinding Lights", artist: "The Weeknd", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Less Than Zero", artist: "The Weeknd", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Toss a Coin to Your Witcher", artist: "The Witcher", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Never Be Alone", artist: "TheFatRat", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Hate Everything About You", artist: "Three Days Grace", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Never Too Late", artist: "Three Days Grace", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Apologize", artist: "Timbaland ft. OneRepublic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Unravel", artist: "Tokyo Ghoul", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Unravel", artist: "Tokyo Ghoul", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Another Love", artist: "Tom Odell", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heal", artist: "Tom Odell", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Butterflies", artist: "Tom Odell ft. Aurora", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Go Solo", artist: "Tom Rosenthal", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Lights Are On", artist: "Tom Rosenthal", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Leave a Light On", artist: "Tom Walker", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Dance Monkey", artist: "Tones and I", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "If You Could Only See", artist: "Tonic", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Africa", artist: "Toto", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Habits (Stay High)", artist: "Tove Lo", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "You've Got a Friend in Me", artist: "Toy Story", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Fast Car", artist: "Tracy Chapman", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Drops of Jupiter", artist: "Train", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Hey, Soul Sister", artist: "Train", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Falling", artist: "Trevor Daniel", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Chlorine", artist: "Twenty One Pilots", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Heathens", artist: "Twenty One Pilots", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "My Blood", artist: "Twenty One Pilots", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Renesmee's Lullaby", artist: "Twilight", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Renesmee's Lullaby", artist: "Twilight", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Megalovania", artist: "Undertale", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Summer Song", artist: "Unnämed", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Like 1999", artist: "Valley", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Like Gold", artist: "Vance Joy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Riptide", artist: "Vance Joy", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "A Thousand Miles", artist: "Vanessa Carlton", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "A Thousand Miles", artist: "Vanessa Carlton", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nothing Stopping Me", artist: "Vicetone ft. Kat Nestel", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Nerve", artist: "Victoria Nadine", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Letter", artist: "VIINI", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wednesday Main Title Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Wednesday Plays The Cello", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "I Wanna Grow Old With You", artist: "Westlife", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Westworld Main Theme", artist: null, notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Last Christmas", artist: "Wham!", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Stone", artist: "Whiskey Myers", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "The Wisp Sings", artist: "Winter Aid", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "House of the Rising Sun", artist: "Wolfenstein The New Order", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Unsteady", artist: "X Ambassadors", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "In The End", artist: "XXXTENTACION", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "SAD!", artist: "XXXTENTACION", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Comptine d’un autre été (Amélie)", artist: "Yann Tiersen", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Kiss The Rain", artist: "Yiruma", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "May Be", artist: "Yiruma", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "River Flows In You", artist: "Yiruma", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "River Flows In You", artist: "Yiruma", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Take On The World", artist: "You At Me Six", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Cough Syrup", artist: "Young The Giant", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Mind Over Matter", artist: "Young the Giant", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Colder Weather", artist: "Zac Brown Band", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Something In The Orange", artist: "Zach Bryan", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Control", artist: "Zee Wees", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
{title: "Happiness Does Not Wait", artist: "Ólafur Arnalds", notes: [ { note: 81, delay: 0, length: 0.66 }, ]},
  
]

export default songs;